# -*- coding: utf-8 -*-
"""Rough.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pL7ytNfARVGMYV3rkNeU-rOR8X44--9f

@author: Joystick


---



*	**Problem Statement**: Wave sort a given array.
        
*	**Time Complexity**: O(n)

*	**Space Complexity**: O(1)
"""

def waveSort(a):
    n = len(a)
    for i in range(0, n-1, 2):

        if i > 0 and a[i-1] > a[i]:
            a[i], a[i-1] = a[i-1], a[i]
            
        if i <= n-2 and a[i+1] > a[i]:
            a[i], a[i+1] = a[i+1], a[i]
    return arr

arr = [1, 3, 4, 2, 7, 8]
print(waveSort(arr))